export const data = [
  {
    id: 1,
    question: 'Bu bir test sorusudur.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'B',
  },
  {
    id: 2,
    question: 'Bu da ikinci soru.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'A',
  },
  {
    id: 3,
    question: 'Bu üçüncü sorudur.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'C',
  },
  {
    id: 4,
    question: 'Dördüncü soru burada.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'D',
  },
  {
    id: 5,
    question: 'Beşinci soru gelmiştir.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'E',
  },
  {
    id: 6,
    question: 'Altıncı soru şimdi karşında.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'A',
  },
  {
    id: 7,
    question: 'Yedinci soru seni bekliyor.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'B',
  },
  {
    id: 8,
    question: 'Sekizinci soru işte burada.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'C',
  },
  {
    id: 9,
    question: 'Dokuzuncu soru sana geliyor.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'D',
  },
  {
    id: 10,
    question: 'Onuncu soru geldi.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'E',
  },
  {
    id: 11,
    question: 'Onbirinci soru başında bekliyor.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'A',
  },
  {
    id: 12,
    question: 'Onikinci soru şimdi karşında.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'B',
  },
  {
    id: 13,
    question: 'Onüçüncü soru seni bekliyor.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'C',
  },
  {
    id: 14,
    question: 'Ondördüncü soru işte burada.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'D',
  },
  {
    id: 15,
    question: 'Onbeşinci soru sana geliyor.',
    options: {
      A: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      B: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      C: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      D: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      E: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    correctAnswer: 'E',
  },
];
